server:
  port: 9999
  context-path: /simulator

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:./repo


hibernate:
  dialect: "org.hibernate.dialect.H2Dialect"

logging:
  level: debug
